name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        ruby: [ 'head', '3.1', '3.0', '2.7', '2.6' ]
        os: [ ubuntu, macos, windows ]
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler
      run: bundle install
    - name: Run test
      run: bundle exec rake
    - id: build
      run: |
        rake build
        echo "::set-output name=pkg::${GITHUB_REPOSITORY#*/}-${RUNNING_OS%-*}"
      env:
        RUNNING_OS: ${{matrix.os}}
      if: "matrix.ruby == '3.1'"
      shell: bash
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        path: pkg/*.gem
        name: ${{steps.build.outputs.pkg}}
      if: steps.build.outputs.pkg
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        ruby: [ '2.5' ]
        os: [ ubuntu, macos, windows ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Bundler
      run: bundle install
    - name: Install gem
      run: bundle exec rake install
